# Generated by Django 2.2 on 2020-07-20 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventHub_app', '0002_category_event'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='creator',
        ),
        migrations.RemoveField(
            model_name='event',
            name='users',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Event',
        ),
    ]
