# Generated by Django 2.2 on 2020-07-21 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventHub_app', '0005_auto_20200720_1929'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='category',
        ),
        migrations.RemoveField(
            model_name='event',
            name='image',
        ),
    ]
