# Generated by Django 2.2 on 2020-07-21 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventHub_app', '0006_auto_20200721_0913'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='end_date',
        ),
    ]
