# Generated by Django 2.2 on 2020-07-21 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventHub_app', '0007_remove_event_end_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Event',
        ),
    ]
