# Generated by Django 2.2 on 2020-07-21 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventHub_app', '0013_event'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Event',
        ),
    ]
